### ISSUE TITLE
ios app stop working

### ISSUE THREAD

**Issue by vladyslav2** [jesusrp98/spacex-go#81]
## Environment

**App version:**  pulled master from github
**Device information:** iPhone 11 Pro Max

## Description
Once I click on any element on the home screen i'm getting black screen with that trace:
```
flutter: #93     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #94     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #95     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #96     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #97     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #98     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #99     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #100    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #102    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #103    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #104    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #105    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #106    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #108    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #109    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #110    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #111    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #112    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #114    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #116    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #117    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #118    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #119    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #120    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #122    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #123    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #124    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #125    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #126    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #127    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #128    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #129    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #130    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #131    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #132    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #133    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534:16)
flutter: #134    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #135    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #136    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #137    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #138    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #140    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #141    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #142    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #143    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #144    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #145    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #146    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #147    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #148    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #149    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #150    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #152    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #153    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #154    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #155    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #156    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #157    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #158    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #159    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #160    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #161    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #162    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #164    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #165    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534:16)
flutter: #166    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #167    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #168    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #169    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #170    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #171    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #172    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #173    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534:16)
flutter: #174    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #175    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #176    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #177    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #178    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #179    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #180    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #181    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #182    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #183    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #184    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #185    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #186    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #187    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #188    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #189    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #190    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #191    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #192    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #193    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #194    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #195    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #196    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #197    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #198    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #199    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #200    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #201    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #202    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #203    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #204    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #205    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #206    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #207    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #208    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #209    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #210    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #211    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #212    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #213    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #214    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #215    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #216    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #217    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #218    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #219    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #220    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #221    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #222    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #223    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #224    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #225    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #226    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #227    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #228    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #229    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #230    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #231    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #232    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #233    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272:14)
flutter: #234    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:308:15)
flutter: #235    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433:14)
flutter: #236    Element.visitChildElements (package:flutter/src/widgets/framework.dart:2921:5)
flutter: #237    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:311:13)
flutter: #238    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:829:53)
flutter: #239    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:804:11)
flutter: #240    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #241    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
flutter: #242    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
flutter: #246    _invoke (dart:ui/hooks.dart:259:10)
flutter: #247    _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jesusrp98** [comment]
This issue is related to the r/SpaceX REST API. There were two separated launches with the same launch id.

This was resolved a couples hours ago, and should be fixed now.
Could you try it again and tell me the result, please? Thanks :)

**Comment by vladyslav2** [comment]
@jesusrp98 sorry! its working now

Do you want to try to publish ios app at this weekend?

**Comment by jesusrp98** [comment]
I've working on the iOS aspect of the app inside the `dev-ios` branch, merged a couple months ago.
There are some things to test before I'm confident to release it to the App Store, such as quick actions functionality, the notifications system etc.

The app is almost ready to launch, I even bought an Apple Developer account, the only thing remaining would be add screenshots, and an app description for the store itself, and this will be time consuming.
Unfortunately, I've been very occupied with college this last months, but I'm finishing it on February. So I'm going to 100% launch the iOS app next month.
